### ISSUE TITLE
Build failed because of vr

### ISSUE THREAD

**Issue by freecates** [GoogleChrome/devsummit#44] opened 2016-11-03 12:18 UTC
Hi,
When building from your github repo with npm run build, it fails at vr stage:

`Could not resolve 'node_modules/three/src/polyfills.js' from /devsummit/scripts/third_party/vrview/src/third_party/three/Three.js`

Attached is the 
[npm-debug.zip](https://github.com/GoogleChrome/devsummit/files/568889/npm-debug.zip)

Thanks a lot for this great PWA!

**Comment by surma** [comment] 2016-11-03 12:32
I can’t reproduce 😕 Which node version are you on?

Here’s my log:

```
$ node --version
v6.9.1
$ yarn
$ npm run build
```

**Comment by freecates** [comment] 2016-11-03 14:54
From my npm-debug.log:

```
17 error Linux 4.8.0-26-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error chrome-dev-summit-2016@4.0.6 build: `npm run build-css && npm run build-js && npm run build-vr && npm run build-resource-list`
22 error Exit status 1
```

Any ideas?

**Comment by surma** [comment] 2016-11-03 15:10
I’ll check this out later, but I assume this is a node 7 issue. Can you use `nvm` to go back to node 6.9 for the time being?

**Comment by ramlmn** [comment] 2016-11-03 15:19
In your case, it looks looks like the `postinstall` script failed after `npm install`. Try running `npm install` again.
If it still fails, try running `cd scripts/third_party/vrview && npm install` manually. Then it should work fine.

*P.S.: Looking at you `PATH`, you seem to not have Java installed. This may cause issues later as `build-vr-deps` script runs 'closure' which needs Java*

**Comment by paullewis** [comment] 2016-11-03 15:31
Epic debugging there, @ramlmn! 👍

**Comment by freecates** [comment] 2016-11-03 15:37
From a fresh pull on 

```
Linux 4.8.0-26-generic
node v6.9.1
npm  v3.10.8
```

First I need to modifiy package.json adding some additional dependencies:

```
  "devDependencies": {
    "eventemitter3": "^2.0.2",
    "tween.js": "^16.3.5",
    "webvr-boilerplate": "^0.4.9",
    "webvr-polyfill": "^0.9.23"
  }
```

And then still failed

```
> vrview@2.0.0-beta.1 build-three-closure /home/rgil/Documents/feina/code-labs-general/devsummit/scripts/third_party/vrview
> rollup -c src/third_party/three/rollup.config.js && java -jar src/third_party/three/closure-compiler-v20160713.jar --warning_level=VERBOSE --jscomp_off=globalThis --jscomp_off=checkTypes --externs src/third_party/three/externs.js --language_in=ECMASCRIPT5_STRICT --js build/three.js --js_output_file build/three.min.js

Could not resolve '../../../node_modules/three/src/polyfills.js' from /home/rgil/Documents/feina/code-labs-general/devsummit/scripts/third_party/vrview/src/third_party/three/Three.js                                                                                                                  
Error: Could not resolve '../../../node_modules/three/src/polyfills.js' from /home/rgil/Documents/feina/code-labs-general/devsummit/scripts/third_party/vrview/src/third_party/three/Three.js                                                                                                           
    at /home/rgil/Documents/feina/code-labs-general/devsummit/node_modules/rollup/src/Bundle.js:319:41                                              
    at process._tickCallback (internal/process/next_tick.js:103:7)                                                                                  
    at Module.runMain (module.js:606:11)                                                                                                            
    at run (bootstrap_node.js:394:7)                                                                                                                
    at startup (bootstrap_node.js:149:9)                                                                                                            
    at bootstrap_node.js:509:3 
``` 

Can you check it?

Thanks.

**Comment by ramlmn** [comment] 2016-11-03 15:43
Try `cd scripts/third_party/vrview && npm install`.
You don't have to modify `devDependencies` in `package.json`, they are already in `dependencies`.

Can I know what distro of Linux are you using?

**Comment by ramlmn** [comment] 2016-11-03 15:43
Epic debugging: [https://gist.github.com/ramlmn/2cd32189e00edfe434e2becf897eca63](https://gist.github.com/ramlmn/2cd32189e00edfe434e2becf897eca63) on Windows(😜) and lot of searching, @paullewis

**Comment by freecates** [comment] 2016-11-03 15:48
Hy @ramlmn running the install on `cd scripts/third_party/vrview/ npm install` and then a `npm run build `works like a charm on `Ubuntu 16.10 x86_64 Linux 4.8.0-26-generic`.

Thanks a lot! @ramlmn !

**Comment by ramlmn** [comment] 2016-11-03 15:57
The problem I think was the syntax of `(cd scripts/third_party/vrview; npm i)`, the `;` thing doesn't work on most terminals.

I had to change `(cd scripts/third_party/vrview; npm i)` to `(cd scripts/third_party/vrview && npm i)`, which apparently seem to work on most terminals.

I also had to change
``` json
"build-vr": "npm run build-vr-deps && npm run build-vr-dev && babel static/scripts/webvr.js --presets babel-preset-babili --out-file static/scripts/webvr.js",
"build-vr-deps": "(cd scripts/third_party/vrview; npm run build && npm run build-api) && cp -r scripts/third_party/vrview static/third_party",
"build-vr-dev": "cat scripts/third_party/vrview/build/vrview.min.js scripts/webvr.js > static/scripts/webvr.js"
```
to
``` json
"build-vr": "npm run build-vr-deps && npm run copy-vr-deps && npm run build-vr-dev && babel static/scripts/webvr.js --presets babel-preset-babili --out-file static/scripts/webvr.js",
"build-vr-deps": "(cd scripts/third_party/vrview && npm run build && npm run build-api)",
"copy-vr-deps": "cp -r scripts/third_party/vrview static/third_party",
"build-vr-dev": "cat scripts/third_party/vrview/build/vrview.min.js scripts/webvr.js > static/scripts/webvr.js"
```
because Bash on Windows doesn't seem to like it.

And finally `"clean-css": "./build/clean-css.js"` to `"clean-css": "node ./build/clean-css.js"`, because Windows(😜, sarcasm)

**Comment by ramlmn** [comment] 2016-11-04 02:50
You can close this issue now @paullewis @surma @freecates.

**Closed** 2016-11-04 09:33 UTC
